source 'https://rubygems.org' do
  gem 'cute_logger'
  gem 'grape'
  gem 'minitest'
  gem 'mysql2'
  gem 'puma'
  gem 'rake'
  gem 'rack-minitest'
  gem 'ruby-ant-server'
  gem 'safe_yaml'
  gem 'sequel'
  gem 'simplecov'
  gem 'rack-cors'
end
